### PR TITLE
Changed error message

### PR DESCRIPTION
**Pull request by elenatorrey**
fixes issue #70 

## Changes in this PR.

- [X] update error message

## Testing this PR.

   1. Run docker-compose run web bash
    2. cd into streamwebs_frontend
    3. Run python manage.py test streamwebs/tests/models

1. Run docker-compose up
2. Go to http://localhost:8000/streamwebs/ 
3. Try bad birth date 

### Expected Output.

If the user inputs bad year, month or day, you will get the same error message. 

 @leian7 @Kennric

### CODE REVIEW

**Comment by leian7** [comment]
Forgot to tell you can reference which issue your PR satisfies! It's the
"fixes issue #xx" part; just replace the xx with your issue's number. I
think in your case it is 70

**Comment by leian7** [comment]
+1

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by Kennric** [comment]
+1

**Pull request merged**
