### PR TITLE
Add flake8 exclusion for migrations folder, and fix docs/source/conf.…

### PR DESCRIPTION
**Pull request by lo9key**
This PR addresses the wall of text we see while running flake9, by adding a flake8 exclusion for the migrations folder and fixing some warnings caused by comments in docs/source/conf.py

## Changes in this PR.

- [X] Fixes flake8 warnings in docs/source/conf.py
- [X] Exclude /streamwebs_frontend/streamwebs/migrations/ from flake8
- [X] Improves output from ./runtests

## Testing this PR.

1. Test flake8
2. Test ./runtests
3. Both tests should pass normally. (branched from develop)

### Expected Output.

Test flake8:
```
# flake8
# 
```
Test ./runtests:
```
# ./runtests.sh 
No changes detected
Operations to perform:
  Apply all migrations: admin, contenttypes, streamwebs, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
  Applying streamwebs.0001_initial... OK
Creating test database for alias 'default'...
.......................................Testing!
.......................................................................
----------------------------------------------------------------------
Ran 110 tests in 1.946s

OK
Destroying test database for alias 'default'...
```

@osuosl/devs

### CODE REVIEW

**Comment by lo9key** [comment]
Maybe this would be a good place to clean up the runtests output, by commenting out or removing these lines (lines 90 & 91 in this PR) in streamwebs_frontend/streamwebs/views.py, per @leian7's suggestion in my other PR?

```
        else:
            print user_form.errors, profile_form.errors
```

**Comment by subnomo** [comment]
@lo9key Would that remove the `Invalid login details` crap? I am in favor of that :+1:

**Comment by alxngyn** [comment]
+1

**Comment by lo9key** [comment]
I probably should have made another commit for resolving the merge conflict instead of squashing..  I'll do that next time.

**Pull request merged**
