### PR TITLE
Materialize Index, Login and Register html

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #116 
## Changes in this PR.

- [X] Materialized Index, login and register templates
- [x] Segment static js script and css style to files in @subnomo's style
## Testing this PR.

1. `cd data_scripts`
2. `python get_schools.py` .
3. start django.
4. See `localhost:8000/streamwebs` and login and "create account" pages.
### Expected Output.

```
Tests should pass 

```

@osuosl/devs

### CODE REVIEW

**Comment by alxngyn** [comment]
needs #66 to be merged first so we can settle any conflicts

**Comment by leian7** [comment]
The "go" button from the index page still exists on the login and register pages:
login

**Comment by alxngyn** [comment]
@leian7 that is part of the i18n stuff. I'm not really sure where to put it

**Comment by subnomo** [comment]
@alxngyn You can stick in into the navbar, see my changes in https://github.com/osuosl/streamwebs/commit/5901394bb83d1e1c56e28fa9f1594ad5969725f0.

**Comment by alxngyn** [comment]
@subnomo 
Should I wait until that PR gets merged?
or
Should I make a PR to your branch?

**Comment by subnomo** [comment]
@alxngyn You can make a PR to that branch. It's been rebased so it should be *relatively* painless. I just have to fix a few bugs before it's ready to be merged.

**Comment by athai** [comment]
Superseded by #161.

**Pull request closed without merging**
