### PR TITLE
Thai/setup travis

### PR DESCRIPTION
**Pull request by athai**
## Changes in this PR.

- [x] Add (working) .travis.yml to repo
- [x] Add script to run tests and linter
- [x] Add status icon to README

## Testing this PR.

N/A

### Expected Output.

Travis successfully runs tests.

### CODE REVIEW

**Comment by athai** [comment]
I'm trying to set up Travis CI to automate the tests within a docker container but it's proving to be more complicated than expected. Currently, what happens is that after building the container, everything stalls b/c the db can't connect to the right port. I'm not sure how to proceed. Any advice would be appreciated.

**Comment by ElijahCaine** [comment]
@athai can you list out exactly what you want travis to do?

Ideally the docker environments we use are just for development. Travis can test the code and ignore the docker parts of this repository since our actual deployment will most likely *not* be in docker. The docker parts of the project does not *need* to be automatically tested, the code on the other hand *does* need to be tested.

If you're sure you want to use docker in the testing environment, [travis has support for a doker service](https://docs.travis-ci.com/user/docker/), which might be worth looking into.

Let me know what all you want travis to do and we can figure out a gameplan to be implemented.

**Comment by athai** [comment]
@ElijahCaine Currently, I'm trying to get travis to:
* Install requirements.txt
* Set up the postgres db
* Lint
* Run tests

But, I'm running into this error: ``psql: FATAL:  role "postgres_user" does not exist`` before it can build the database.

**Comment by Kennric** [comment]
All checks have passed :) +1

**Pull request merged**
