### PR TITLE
settings.py --> settings.py.dist

### PR DESCRIPTION
**Pull request by leian7**
## Changes in this PR.

- [X] Renames settings.py to settings.py.dist
- [X] Edits .travis.yml so checks can still run
- [X] Edits README to include cp instructions
- [X] Adds settings.py to .gitignore

## Testing this PR.

_1. ``cd streamwebs_frontend/streamwebs_frontend``
2. ``cp settings.py.dist settings.py``_
3. ``sudo docker-compose run web bash``
4. ``cd streamwebs_frontend``
5. ``python manage.py test streamwebs/tests/*``

### Expected Output.

All tests should be able to run and pass.

@Kennric @subnomo @athai @alxngyn @LyonesGamer

### CODE REVIEW

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by alxngyn** [comment]
two things:
* Why are we doing this? Is there something we need to configure for settings.py? issue #?
* Add to .gitignore for settings.py so nobody will accidently commit their file in the future

**Comment by subnomo** [comment]
@alxngyn Yeah there's no issue for this, but there are some things we might want to configure, such as `DEBUG` and `SECRET_KEY`.

I agree that settings.py needs to be in the .gitignore, -1 until then.

**Comment by subnomo** [comment]
+1

**Comment by alxngyn** [comment]
+1

**Pull request merged**
