### PR TITLE
Server Side Validation Example (ignore django->not to be merged)

### PR DESCRIPTION
**Pull request by baileysingleton**
fixes issue #482 and the big issue of validation

## Changes in this PR.

The goal of this PR is to create a consistent validation method that will work across all browsers. This method uses django's built in validation, and a small amount of javascript and CSS to tie it all together. The goal was to remove the client-side issues that plague different browsers for different reasons. This should create a uniform and accurate way to check data and notify user.

The flow of error catching:
1. User submits a form, sending a post request
2. Django's general.py runs it's form.is_valid() function  to check the data, which runs a clean() function
3. This clean() function can be overridden in the forms.py, to check for additional parameters (in my example, this is checking the length of the submitted name)
4. The errors are then sent to the html, where Javascript handles it and outputs it as a toast message
5. CSS manipulates the bottom border of each field to give a visual clue as to which fields are wrong.

## Testing this PR.

1. navigate to localhost:8000/test
2. Submit blank form, see toast in top right notifying you, and see bottom border color change
3. Add some wonky data, name is limited to 10 characters, see if other invalid data errors show

I'm not sure if you have to makemigrations and migrate, but if things aren't working:
docker-compose run web bash
python streamwebs_frontend/manage.py makemigrations
python streamwebs_frontend/manage.py migrate

### Expected Output.

Submitting incorrect form yields: (note the first field and it's error, set in forms.py) 
full errors

Submittin
some errors

```
$ make test
[... test output ...]
```

@osuosl/devs

### CODE REVIEW

**Comment by JerryPeng0112** [comment]
@baileysingleton Works great

**Comment by ramereth** [comment]
@baileysingleton why did you re-open this if it's an example?

**Comment by hertelc** [comment]
@baileysingleton @ramereth   Can we close this PR since it was an example?

**Comment by CarvellWakeman** [comment]
Closed because it's an example and is being implemented now

**Pull request closed without merging**
