### PR TITLE
Fix data popups for browsers such as MS Edge

### PR DESCRIPTION
**Pull request by baileysingleton**
… login to index

fixes issue #482 

## Changes in this PR.

- [X] Macroinvertebrates has a toast message now
- [X] Login  redirects to index.html

## Testing this PR.

0. Be on windows machine with microsoft edge
1. Go to any datasheet
2. try to submit
3. See if toast pops up

### Expected Output.

```
$ make test
[... test output ...]
```

@osuosl/devs

### CODE REVIEW

**Comment by JerryPeng0112** [comment]
Cannot make redirection point to the index.html. The redirection is meant for users who are not logged in and are trying to create datasheets. Since users who are not logged in are not allowed to create datasheets, they are redirected to login screen, after login the pages redirect to the add datasheet pages.
So in essence, the way to fix it should be redirect to index.html only when user was going to be redirected to register.html

**Comment by hertelc** [comment]
@clementsm or @ramereth  can we work on getting this through review please?  Thanks!

**Comment by ramereth** [comment]
@hertelc this isn't ready for review and @baileysingleton is working on implementing this with proper server-side validation instead.

**Comment by hertelc** [comment]
@baileysingleton what is the status here please?

**Comment by CarvellWakeman** [comment]
Closed because #575 will replace it

**Pull request closed without merging**
