### PR TITLE
Custom datepicker

### PR DESCRIPTION
**Pull request by JerryPeng0112**
fixes issue #490 

NOT READY FOR REVIEW YET
## Changes in this PR.

- [X] Cleared all datepicker from Materialize CSS
- [X] Created small javascript for the date picker
- [X] Implemented to most sites with date (besides graph sites)
- [x] Make sure birthdate for registration's error handling gets propagated to custom date fields
- [X] Added front-end implementation to prevent future date being entered
- [x] Add back end validation for future dates
- [x] graph's date fields implemented

## Testing this PR.

The datepicker basically create a dropdown of year/monty/day, and does no error handling during submission. If the form returns an error, for date, the javascript will append the error message.
Just like normal calendar, February has 29 days for leap years. 
If a user chose 1997/01/31, and decided to change the month to February, because February only have 28/29 days, the day field will be cleared.
IMPORTANT: I strongly advise to test all of the steps below for every site. Good luck.
1. For every form, first, without entering date and with all other required fields filled, submit data. See if the form gets rejected and all error message are displayed.
2. Second, choose a date with year/month/day filled. Intentionally make a field invalid (for example: 12:3333 for time field). The form will get rejected, see if the date fields data are still presents, if it gets reset please report.
3. Third, mess around with the dates. For example, input 1997/01/31, and change month to February, check if day field gets cleared. Or choose 2016/02/29 (leap year), and change year to 2015 (non-leap year) and see if day field gets cleared.
4. Clear all fields by refreshing, (Ctrl-shift-R on chrome), and choose current year (2017), check if December is hidden (If it is November now), Then click the november, see if all the future dates are hidden.

Special Cases: For register, input a birthday that is less than 13 years old. See if the error shows up. If not please comment.

### Expected Output.
1. All error message present for date fields with empty data
2. All date fields are not reset
3. the day field gets cleared when current value is larger than the amount of days the month have.
4. All future dates hidden
5. For birthday, if birthday is less than 13 years old, it outputs error.

```
$ make test
[... test output ...]
```

@osuosl/devs

### CODE REVIEW

**Comment by clementsm** [comment]
The dropdowns seem functional. We should probably give them a test on an ipad to be sure that will work.

**Comment by JerryPeng0112** [comment]
@clementsm Will do

**Comment by hertelc** [comment]
@CarvellWakeman when you get a chance, would you please review this item and update it to be able to merge in our next staging push?  This was a specific feature request from StreamWebs.

**Comment by CarvellWakeman** [comment]
We're holding off on implementing this just yet

**Pull request closed without merging**
