### PR TITLE
Alxngyn/users profile mod

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #141 

## Changes in this PR.

- [X] Updated schools in the models.py to take a userprofile
- [X] Updated/removed old tests relating to the old "schools choices"

## Testing this PR.

1. Do `runtests.sh`
2. All tests should pass.

### Expected Output.

```
./runtests.sh
...

Ran 105 tests in 2.759s

OK
```

@osuosl/devs

### CODE REVIEW

**Comment by leian7** [comment]
Looks good. Can you also register School in admin.py?

**Comment by athai** [comment]
+1

**Comment by alxngyn** [comment]
@leian7 that was covered in the schools model PR.
https://github.com/osuosl/streamwebs/blob/develop/streamwebs_frontend/streamwebs/admin.py#L15

**Comment by leian7** [comment]
+1

**Comment by Kennric** [comment]
+1

**Pull request merged**
