### PR TITLE
School search functionality in datasheets and register

### PR DESCRIPTION
**Pull request by JerryPeng0112**
fixes issue #487 

## Changes in this PR.

- [X] Implement the search school functionality in all datasheets. all in a .js file
- [X] Corrected camera point coordinate format when posting data, to match the ones from drupal.
- [X] Errors on form does not make the school selection return to default

## Testing this PR.

Sites to be tested: add macroinvertebrate, camera_point, canopy_cover, rip_aqua, rip_trans, soil, water_quality, and register.html
For each site do the following:
1. search for a school: click on the school you'd like to select. Make sure the highlighted school name in "school selection: " is the school you'd like to select. Complete the form and submit, make sure the school name is correct.
2. search for a school, rather than submitting a good form, create an intentional error.
(easiest way: for most datasheets, fill invalid data for time field, ex: "12:123", or for integer field, enter a very large integer that is more than a trillion, or for register.html, select your birth date as today, which will trigger an error since user has to be at least 13 years old.
3. This time, for the same site, don't search for a school. complete the form and submit. After submission make sure the school is the default school, which is the first school in alphabetical order.

### Expected Output.

Everything works, reference above for expected output.

```
$ make test
[... test output ...]
```

@osuosl/devs

### CODE REVIEW

**Comment by JerryPeng0112** [comment]
@ramereth Oops, forgot to add it. Now it's gone, lemme try to pull it from my browser cache

**Comment by JerryPeng0112** [comment]
@ramereth Got the file back, please help me reveiw it thanks. I will be back on Wed.

**Comment by ramereth** [comment]
@hertelc this has been deployed at http://streamwebs-dev.osuosl.org:8000/ for testing

**Comment by JerryPeng0112** [comment]
@ramereth It did not work on my iphone, I need to do more testing on this

**Comment by CarvellWakeman** [comment]
Working on rewriting this with a more elegant solution - currently the styling on this does not work.
The drop down is filled with white buttons with white text, and overlaps everything on the page.

**Pull request closed without merging**
