### PR TITLE
HTML template for water quality datasheet

### PR DESCRIPTION
**Pull request by matthewrsj**
ref #11

### CODE REVIEW

**Comment by matthewrsj** [comment]
HTML page without CSS took me 1.5 hours (8:15am - 9:45am)

**Comment by matthewrsj** [comment]
Currently:

**Comment by matthewrsj** [comment]
I'm not sure how much CSS we want to incorporate now before we adopt a framework.

Time worked on this commit: 40 minutes
Total time worked so far: 2 hours 10 minutes

**Comment by matthewrsj** [comment]
Added the vernier/manual options

Time worked on this commit: 10 minutes
Total time worked so far: 2 hours 30 minutes

**Comment by matthewrsj** [comment]
Currently:

**Comment by LyonesGamer** [comment]
This PR is outdated at this point and has been superseded by other code.

**Pull request closed without merging**
