### PR TITLE
Thai/fixup tests

### PR DESCRIPTION
**Pull request by athai**
fixes issue #51

## Changes in this PR.

- [X] Fix typos in Water Quality field name
- [X] Add a missing tests for the WQ datasheet
- [X] Add docstrings to tests

## Testing this PR.

1. ``docker-compose run web bash`` 
2. ``cd streamwebs_frontend``
3. ``python manage.py test streamwebs/tests/*``

### Expected Output.

```
[root@3fcc7c4d595e streamwebs_frontend]# python manage.py test streamwebs/tests/*      
Creating test database for alias 'default'...
............................Invalid login details: notjohn, badpassword
.Invalid login details: notjohn, johnpassword
.Invalid login details: john, badpassword
.....<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field is required.</li></ul></li></ul> <ul class="errorlist"><li>school<ul class="errorlist"><li>This field is required.</li></ul></li><li>birthdate<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
...
----------------------------------------------------------------------
Ran 38 tests in 1.050s

OK
Destroying test database for alias 'default'...

```

### CODE REVIEW

**Comment by leian7** [comment]
Were you also going to do a test_optional_fields test for test_wq_sample like you did for test_water_quality?

**Comment by leian7** [comment]
@alxngyn left me this comment https://github.com/osuosl/streamwebs/pull/60/files/a9b45cc32eb25c7666ad9550f90817fda00b7edf#r70322418 about increasing the digits and decimal places for latitude and longitude fields

**Comment by alxngyn** [comment]
+1

**Comment by Kennric** [comment]
+1

**Pull request merged**
