### PR TITLE
Leian/re recaptcha

### PR DESCRIPTION
**Pull request by leian7**
Probably fixes issue #50 and #72  ...

## Changes in this PR.

- [X] Adds Google's "no-captcha recaptcha" to registration via [django-recaptcha](https://github.com/praekelt/django-recaptcha)
- [X] Tests the functionality of both the captcha and the built-in captcha testing mode
- [X] Further fleshes out registration tests (+email is now a required field)

## Testing this PR.

To run tests:
1. Run ``docker-compose run web bash`` to open up an interactive shell
2. ``cd`` into ``streamwebs_frontend/``
3. Run ``python manage.py test streamwebs/tests/forms`` and ``python manage.py test streamwebs/tests/views`` (or ``python manage.py test streamwebs/tests/*`` to run all the tests) 

To see it in action in-browser:
1. Run ``docker-compose up``
2. Go to http://localhost:8000/streamwebs/ and click "register"

### Expected Output.

```
[root@5ec97e04c726 streamwebs_frontend]# python manage.py test streamwebs/tests/*
Creating test database for alias 'default'...
...........................<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field is required.</li></ul></li><li>email<ul class="errorlist"><li>This field is required.</li></ul></li></ul> <ul class="errorlist"><li>captcha<ul class="errorlist"><li>This field is required.</li></ul></li><li>school<ul class="errorlist"><li>This field is required.</li></ul></li><li>birthdate<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
. <ul class="errorlist"><li>captcha<ul class="errorlist"><li>Incorrect, please try again.</li></ul></li></ul>
. <ul class="errorlist"><li>captcha<ul class="errorlist"><li>Incorrect, please try again.</li></ul></li></ul>
...Invalid login details: notjohn, badpassword
.Invalid login details: notjohn, johnpassword
.Invalid login details: john, badpassword
.....
----------------------------------------------------------------------
Ran 39 tests in 1.273s

OK
Destroying test database for alias 'default'...
```
captcha_reg

### Notes.
When you run ``python manage.py test captcha`` you actually get a test failure:
```
[root@5ec97e04c726 streamwebs_frontend]# python manage.py test captcha
Creating test database for alias 'default'...
.F
======================================================================
FAIL: test_envvar_enabled (captcha.tests.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/captcha/tests.py", line 19, in test_envvar_enabled
    self.assertTrue(form.is_valid())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...
```
The test in question is can be viewed [here](https://github.com/praekelt/django-recaptcha/blob/develop/captcha/tests.py). It only tests the functionality of their RECAPTCHA_TESTING environmental variable. I put near-identical tests in ``streamwebs_frontend/streamwebs/tests/views/test_registration_view.py`` and they pass, indicating that their test mode does work. In addition, the captcha itself works exactly as expected, both in my tests and in the browser.

@Kennric @athai @alxngyn @subnomo @LyonesGamer

### CODE REVIEW

**Comment by alxngyn** [comment]
I'm getting this when I try to run makemigrations:
```
ImportError: cannot import name ReCaptchaField
```
Do you know what I need to do to fix it?

**Comment by leian7** [comment]
I changed requirements.txt to order to install django-recaptcha, so you
might have to rebuild your container if you haven't already?

**Comment by alxngyn** [comment]
works! +1
```
[root@48fba16f7676 streamwebs_frontend]# python manage.py test streamwebs/tests/*
Creating test database for alias 'default'...
Destroying old test database for alias 'default'...
...........................Invalid login details: notjohn, badpassword
.Invalid login details: notjohn, johnpassword
.Invalid login details: john, badpassword
.....<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field is required.</li></ul></li><li>email<ul class="errorlist"><li>This field is required.</li></ul></li></ul> <ul class="errorlist"><li>captcha<ul class="errorlist"><li>This field is required.</li></ul></li><li>school<ul class="errorlist"><li>This field is required.</li></ul></li><li>birthdate<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
. <ul class="errorlist"><li>captcha<ul class="errorlist"><li>Incorrect, please try again.</li></ul></li></ul>
. <ul class="errorlist"><li>captcha<ul class="errorlist"><li>Incorrect, please try again.</li></ul></li></ul>
...
----------------------------------------------------------------------
Ran 39 tests in 1.413s

OK
Destroying test database for alias 'default'...

```

**Comment by cthalmann** [comment]
:+1: really cool!

**Pull request merged**
