### PR TITLE
Make line graph linear, add data points, condense points to 1 per day.

### LINKED ISSUE #170: Various line graph problems
So the line graph for Shafer Creek looks something like this currently:

The problem is that there's a data point for April 17th, about 10 for April 22nd all over the course of about 2 hours, and another 8 for April 23rd all within a few hours. Each with wildly varying data. The data changes too much over too short a time frame for the image to actually be large enough to show, and you get... that.

So, there are a few necessary fixes:

1. Add data points. Each point in the data should have a physical point on the graph, to help ground the lines.
2. Reduce the data down to one point per day. Each point will be the average of the data recorded that day. 
3. Make the graph actually linear. Due to a change in D3 v4 (which provides several pre-made curve generators, including a linear one) from v3 (where the curve needed to be configured by the user, but defaulted to linear), the line is now being drawn as a Bezier curve, which is a bad idea.

### PR DESCRIPTION
**Pull request by LyonesGamer**
Fixes #170.

## Changes in this PR.

- [X] Added data points to the macroinvertebrates line graph.
- [X] Made the graph linear between points instead of using a curve
- [X] Reduced the points to showing a daily average instead of each recorded point.
- [X] Display the legend alongside the lines instead of at the top, out of order.

## Testing this PR.

1. Visit the macro graph page for a site with lots of macro data (I might recommend Shafer Creek).

### Expected Output.

A graph which accurately shows the data with the elements listed above, such as:

@osuosl/devs

### CODE REVIEW

**Comment by athai** [comment]
The labels are overlapping. It might be better to put them in a legend, similar to what you did for the pie chart.

**Comment by LyonesGamer** [comment]
With the labels moved into a legend, the graph now looks like this:

**Comment by athai** [comment]
Lgtm. +1

**Comment by subnomo** [comment]
Nice comments, :+1:

**Pull request merged**
