### PR TITLE
Alxngyn/schools migration

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #122 
relies on pr #123

## Changes in this PR.

- [X] get_schools.py
- [X] edited headers of schools_info.csv

## Testing this PR.

1. `./runtests.sh`.
3. ``cd data_scripts/``
4. Run ``./get_schools.py``
5. ``cd ../streamwebs_frontend``
6. ``python manage.py dbshell``
7. ``SELECT * FROM streamwebs_school;``

### Expected Output.

```
./runtests.sh pass

streamwebs=# select * from streamwebs_school limit 1;
 id |              name              | school_type |     address     |  city   |
  zipcode   |           created            |           modified            |    
   province        
----+--------------------------------+-------------+-----------------+---------+
------------+------------------------------+-------------------------------+----
-------------------
  1 | A C Houghton Elementary School | Elementary  | 1105 N Main Ave | Irrigon |
 97844-7050 | 2016-08-24 23:11:02.78487+00 | 2016-08-24 23:11:02.784888+00 | Ore
gon, United States
(1 row)

streamwebs=# select count(*) from streamwebs_school;
 count 
-------
  5592
(1 row)

```

@osuosl/devs

### CODE REVIEW

**Comment by athai** [comment]
One of the tests is failing for me when I try ``./runtests.sh``. Did you encounter this error?
```
======================================================================
ERROR: test_edge_year_edge_month_bad_day (test_user_model.UserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/streamwebs/streamwebs_frontend/streamwebs/tests/models/test_user_model.py", line 147, in test_edge_year_edge_month_bad_day
    birthdate=datetime.date(today.year-13, today.month, today.day+1)
ValueError: day is out of range for month

----------------------------------------------------------------------
Ran 107 tests in 2.905s

FAILED (errors=1)
```

**Comment by athai** [comment]
Also, can you add School to admin.py? So that the table can be viewed from the Django admin panel.

**Comment by leian7** [comment]
@athai @alxngyn That test failure is my bad. Today is the 31st, so obviously ``today.day+1`` is not a thing. Here's [a quick diff](https://pastebin.osuosl.org/42506/) to get this test to pass again; hopefully it's not horrendously wrong.

**Comment by leian7** [comment]
+1, it works. To nitpick:

Not sure if this is just something on my end:
```
[root@fb0dddd6e335 streamwebs]# cd data_scripts/
[root@fb0dddd6e335 data_scripts]# ls             
get_macros.py  get_schools.py  get_sites.py
```
get_schools.py wasn't highlighted, and when I tried doing:
```
[root@fb0dddd6e335 data_scripts]# ./get_schools.py
bash: ./get_schools.py: Permission denied
```
I had to do ``python2 get_schools.py`` to get it to run.

**Comment by athai** [comment]
Lgtm. +1

**Comment by leian7** [comment]
+1

**Pull request merged**
