### PR TITLE
Riparian Aqua Survey datasheet model 

### PR DESCRIPTION
**Pull request by alxngyn**
fixes issue #56 
## Changes in this PR.

- [X] Riparian Aqua Survey Model
- [X] Tests
## Testing this PR.

1. `sudo docker-compose run web bash`
2. `cd streamwebs_frontend/`
3. `python manage.py makemigrations`
4. `python manage.py migrate`
5. `python manage.py test streamwebs/tests/models/`
### Expected Output.

```
[root@80d921aecbf2 streamwebs_frontend]# python manage.py test streamwebs/tests/models/
Creating test database for alias 'default'...
.........................
----------------------------------------------------------------------
Ran 25 tests in 0.455s

OK
Destroying test database for alias 'default'...
[root@80d921aecbf2 streamwebs_frontend]# 
```

@osuosl/devs

### CODE REVIEW

**Comment by mathuin** [comment]
That's an impressive set of flake8 errors. :-)

**Comment by leian7** [comment]
+1. Do you want to add the Ready For Review label?

**Comment by alxngyn** [comment]
@leian7 done

**Comment by Kennric** [comment]
This is looking pretty good to me +1

**Comment by Kennric** [comment]
@alxngyn what is the status of this?

**Comment by alxngyn** [comment]
@Kennric I was told that Riparian and Aquatic Survey datasheets would change. I think we are waiting on the client for the final datasheet so we can create the model/views etc. For now this is just blocked until then.

**Pull request closed without merging**
