### PR TITLE
Leian/index

### PR DESCRIPTION
**Pull request by leian7**
Addresses issue #20 

## Changes in this PR.

- [X] Test static index view (correct template and HTTP status code)
- [X] Implement static index view with template 

## Testing this PR.

1. Start up an instance of the StreamWebs docker container
2. Log into the container w/ docker-compose run web bash
3. cd into /streamwebs_frontend
4. Run python manage.py test streamwebs/tests/views

### Expected Output.

The test should pass.

@Kennric @athai

### CODE REVIEW

**Comment by Kennric** [comment]
Works for me. +1

**Comment by matthewrsj** [comment]
@leian7 wasn't this included in PR #25? This is a better place for the test, regardless.

**Comment by leian7** [comment]
Yeah, this test should be in this PR and not the docs one.

**Comment by athai** [comment]
Works for me. Just fix those merge conflicts and you'll be good to merge! +1

**Pull request merged**
